import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase/database.types';

type _ViewRow = Database['public']['Views']['trails_view']['Row'];

/**
 * Narrowed TrailRow type: overrides the codegen view row (where all columns are
 * nullable) with the actual NOT NULL constraints from the underlying `trails`
 * table. Nullable-in-DB columns remain `| null`.
 *
 * Do NOT edit database.types.ts — it is autogenerated. Maintain nullability
 * overrides here instead.
 */
export type TrailRow = Omit<
  _ViewRow,
  | 'id'
  | 'name'
  | 'type'
  | 'bike'
  | 'connector'
  | 'hidden'
  | 'planned'
  | 'region_id'
  | 'visibility'
  | 'created_at'
  | 'updated_at'
> & {
  id: number;
  name: string;
  type: string;
  bike: boolean;
  connector: boolean;
  hidden: boolean;
  planned: boolean;
  region_id: number;
  visibility: string;
  created_at: string;
  updated_at: string;
  /**
   * True when the elevation profile is missing entirely or geometry has
   * changed since the profile was last computed. The Python elevation app
   * uses this to know which trails need reprocessing.
   * elevation_coords will be NULL whenever this is true.
   */
  elevation_stale: boolean;
  /**
   * Elevation profile vertices from trail_elevations.geom4d, pre-computed by
   * the view. Each inner array is [lng, lat, elevation_m, distance_m].
   * NULL when elevation_stale is true.
   */
  elevation_coords: number[][] | null;
};

export interface GetTrailsDbArgs {
  /** When true, hidden trails are included (subject to RLS). */
  hidden?: boolean;
  /** When provided, only trails with these ids are returned. */
  ids?: number[];
}

export interface GetTrailsDbResult {
  data: TrailRow[] | null;
  error: Error | null;
}

/** Fetches trails from the `trails_view` view. RLS enforced server-side. */
export async function getTrailsDb(
  client: SupabaseClient<Database>,
  { hidden = false, ids }: GetTrailsDbArgs = {}
): Promise<GetTrailsDbResult> {
  let query = client.from('trails_view').select('*').order('id');

  if (!hidden) {
    query = query.eq('hidden', false);
  }

  if (ids !== undefined && ids.length > 0) {
    query = query.in('id', ids);
  }

  const { data, error } = await query;

  if (error) return { data: null, error: new Error(error.message) };
  return { data: data as unknown as TrailRow[], error: null };
}
