-- Trails table + attribution
-- Stores trail metadata and geometry (LineString, WGS84 / EPSG:4326)
--
-- Visibility (restriction column):
--   'public'     → readable by everyone (anon + authenticated)
--   'user'       → readable only by attributed profile(s) + admins
--   'admin_only' → readable only by admins
--
-- Write access: admins only (insert / update / delete)

create extension if not exists postgis;

-- ============================================================
-- Trails
-- ============================================================
create table public.trails (
  id             bigint generated by default as identity primary key,
  created_at     timestamp with time zone not null default now(),
  updated_at     timestamp with time zone not null default now(),

  -- Identity
  name           text not null,
  type           text not null,              -- e.g. 'singletrack', 'doubletrack', 'road'
  trail_class    text,                       -- e.g. 'TC1'–'TC5'
  activity_types text[],                     -- e.g. '{hiking,mtb}'
  direction      text,                       -- 'both', 'oneway', 'oneway-reverse'

  -- Flags
  hidden         boolean not null default false,
  planned        boolean not null default false,
  connector      boolean not null default false,
  bike           boolean not null default false,

  -- Stats
  tf_popularity  numeric,                    -- Trailforks popularity score

  -- Access control
  restriction    text not null default 'public'
                   check (restriction in ('public', 'user', 'admin_only')),

  -- Spatial — LineString in WGS84 (EPSG:4326)
  geometry       geometry(LineString, 4326) not null
);

comment on table  public.trails                  is 'Trail network segments';
comment on column public.trails.type             is 'Trail surface/type classification';
comment on column public.trails.trail_class      is 'Difficulty class (TC1–TC5)';
comment on column public.trails.activity_types   is 'Supported activities e.g. hiking, mtb';
comment on column public.trails.direction        is 'Travel direction: both | oneway | oneway-reverse';
comment on column public.trails.hidden           is 'Hidden from public view';
comment on column public.trails.planned          is 'Planned/proposed trail, not yet built';
comment on column public.trails.connector        is 'Connector segment between main trails';
comment on column public.trails.bike             is 'Bikeable segment';
comment on column public.trails.tf_popularity    is 'Trailforks popularity score';
comment on column public.trails.restriction      is 'public | user | admin_only';
comment on column public.trails.geometry         is 'LineString geometry in WGS84 (EPSG:4326)';

-- Spatial index for fast geo queries
create index trails_geometry_idx on public.trails using gist (geometry);

-- updated_at trigger (reuses function created in permissions migration)
create trigger trails_set_updated_at
  before update on public.trails
  for each row execute function public.set_updated_at();

-- ============================================================
-- Trail attribution
-- Links a trail to specific profiles when restriction = 'user'
-- ============================================================
create table public.trail_attribution (
  id         bigint generated by default as identity primary key,
  trail_id   bigint not null references public.trails   (id) on delete cascade,
  profile_id bigint not null references public.profiles (id) on delete cascade,
  constraint trail_attribution_unique unique (trail_id, profile_id)
);

comment on table  public.trail_attribution            is 'Attributes a trail to specific profiles (used when restriction = ''user'')';
comment on column public.trail_attribution.trail_id   is 'The restricted trail';
comment on column public.trail_attribution.profile_id is 'Profile that can access the trail';

create index trail_attribution_trail_id_idx   on public.trail_attribution (trail_id);
create index trail_attribution_profile_id_idx on public.trail_attribution (profile_id);

-- ============================================================
-- RLS — trails
-- ============================================================
alter table public.trails enable row level security;

-- Helper: is the calling user attributed to this trail?
create or replace function public.is_attributed_to_trail(trail_id bigint)
returns boolean language sql security definer stable as $$
  select exists (
    select 1
    from public.trail_attribution ta
    join public.profiles p on p.id = ta.profile_id
    where ta.trail_id = $1
      and p.auth_user_id = auth.uid()
  );
$$;

-- SELECT
--   public trails visible to everyone
--   user-restricted trails visible to attributed profiles + admins
--   admin_only trails visible to admins only
create policy "trails: select"
  on public.trails for select
  using (
    restriction = 'public'
    or public.is_admin()
    or (restriction = 'user' and public.is_attributed_to_trail(id))
  );

-- INSERT / UPDATE / DELETE — admins only
create policy "trails: admins insert"
  on public.trails for insert
  with check (public.is_admin());

create policy "trails: admins update"
  on public.trails for update
  using  (public.is_admin())
  with check (public.is_admin());

create policy "trails: admins delete"
  on public.trails for delete
  using (public.is_admin());

-- ============================================================
-- RLS — trail_attribution
-- ============================================================
alter table public.trail_attribution enable row level security;

-- Attributed users can see their own attribution rows; admins see all
create policy "trail_attribution: select"
  on public.trail_attribution for select
  using (
    public.is_admin()
    or public.is_attributed_to_trail(trail_id)
  );

-- Admins manage all attribution
create policy "trail_attribution: admins insert"
  on public.trail_attribution for insert
  with check (public.is_admin());

create policy "trail_attribution: admins update"
  on public.trail_attribution for update
  using (public.is_admin());

create policy "trail_attribution: admins delete"
  on public.trail_attribution for delete
  using (public.is_admin());

-- ============================================================
-- Grants
-- ============================================================
grant select           on public.trails            to anon, authenticated;
grant all              on public.trails            to service_role;
grant all              on sequence public.trails_id_seq to service_role;

grant select           on public.trail_attribution to anon, authenticated;
grant all              on public.trail_attribution to service_role;
grant all              on sequence public.trail_attribution_id_seq to service_role;

