-- ============================================================
-- Initial schema: regions, profiles, trails, RBAC
-- ============================================================

-- ============================================================
-- Extensions
-- ============================================================
create extension if not exists postgis;

-- ============================================================
-- Enums
-- ============================================================
create type public.app_role as enum ('super_admin', 'admin', 'super_user', 'user');

-- ============================================================
-- Shared trigger function
-- ============================================================
create function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- Regions
-- ============================================================
create table public.regions (
  id   bigint generated by default as identity primary key,
  name text not null unique
);

comment on table public.regions is 'Geographic regions for scoping access';

alter table public.regions enable row level security;

create policy "regions: select" on public.regions for select using (true);
create policy "regions: service_role manage" on public.regions for all
  using (auth.role() = 'service_role');

grant select on public.regions to anon, authenticated;
grant all on public.regions to service_role;
grant all on sequence public.regions_id_seq to service_role;

-- ============================================================
-- Profiles
-- ============================================================
create table public.profiles (
  id           bigint generated by default as identity primary key,
  created_at   timestamp with time zone not null default now(),
  auth_user_id uuid not null,
  name         text not null,
  role         public.app_role not null default 'user',
  region_id    bigint not null references public.regions (id),
  phone        text,
  bio          text
);

CREATE UNIQUE INDEX profiles_name_key ON public.profiles USING btree (name);

alter table public.profiles add constraint "profiles_auth_user_id_fkey"
  FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table public.profiles validate constraint "profiles_auth_user_id_fkey";

alter table public.profiles add constraint "profiles_name_key"
  UNIQUE using index "profiles_name_key";

alter table public.profiles enable row level security;

grant select on table public.profiles to anon;
grant select, insert, update on table public.profiles to authenticated;
grant all on table public.profiles to service_role;

-- ============================================================
-- Trails
-- ============================================================
create table public.trails (
  id             bigint generated by default as identity primary key,
  created_at     timestamp with time zone not null default now(),
  updated_at     timestamp with time zone not null default now(),

  name           text not null,
  type           text not null,
  trail_class    text,
  activity_types text[],
  direction      text,

  hidden         boolean not null default false,
  planned        boolean not null default false,
  connector      boolean not null default false,
  bike           boolean not null default false,

  tf_popularity  numeric,

  visibility     text not null default 'public'
                   check (visibility in ('public', 'private', 'shared')),

  region_id      bigint not null references public.regions (id),

  geometry       geometry(LineString, 4326) not null
);

comment on table  public.trails                  is 'Trail network segments';
comment on column public.trails.type             is 'Trail surface/type classification';
comment on column public.trails.trail_class      is 'Difficulty class (TC1–TC5)';
comment on column public.trails.activity_types   is 'Supported activities e.g. hiking, mtb';
comment on column public.trails.direction        is 'Travel direction: both | oneway | oneway-reverse';
comment on column public.trails.hidden           is 'Hidden from public view';
comment on column public.trails.planned          is 'Planned/proposed trail, not yet built';
comment on column public.trails.connector        is 'Connector segment between main trails';
comment on column public.trails.bike             is 'Bikeable segment';
comment on column public.trails.tf_popularity    is 'Trailforks popularity score';
comment on column public.trails.visibility       is 'public | private | shared';
comment on column public.trails.geometry         is 'LineString geometry in WGS84 (EPSG:4326)';

create index trails_geometry_idx on public.trails using gist (geometry);

create trigger trails_set_updated_at
  before update on public.trails
  for each row execute function public.set_updated_at();

alter table public.trails enable row level security;

grant select on public.trails to anon, authenticated;
grant all on public.trails to service_role;
grant all on sequence public.trails_id_seq to service_role;

-- ============================================================
-- Helper functions
-- ============================================================

-- Is the calling user an admin (admin or super_admin)?
create or replace function public.is_admin()
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.profiles
    where auth_user_id = auth.uid()
      and role in ('super_admin', 'admin')
  );
$$;

-- Get the calling user's role
create or replace function public.get_my_role()
returns public.app_role language sql security definer stable as $$
  select role from public.profiles
  where auth_user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.get_my_role() to authenticated;

-- Get the calling user's region_id
create or replace function public.get_my_region_id()
returns bigint language sql security definer stable as $$
  select region_id from public.profiles
  where auth_user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.get_my_region_id() to authenticated;

-- ============================================================
-- RLS — profiles
-- ============================================================

-- SELECT
create policy "profiles: select own"
  on public.profiles for select
  using (auth_user_id = auth.uid());

create policy "profiles: super_admin select all"
  on public.profiles for select
  using (public.get_my_role() = 'super_admin');

create policy "profiles: admin select local"
  on public.profiles for select
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- INSERT
create policy "profiles: super_admin insert"
  on public.profiles for insert
  with check (public.get_my_role() = 'super_admin');

create policy "profiles: admin insert local"
  on public.profiles for insert
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- UPDATE
create policy "profiles: update own"
  on public.profiles for update
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

create policy "profiles: super_admin update any"
  on public.profiles for update
  using (public.get_my_role() = 'super_admin')
  with check (public.get_my_role() = 'super_admin');

create policy "profiles: admin update local"
  on public.profiles for update
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- DELETE
create policy "profiles: super_admin delete"
  on public.profiles for delete
  using (public.get_my_role() = 'super_admin');

create policy "profiles: admin delete local"
  on public.profiles for delete
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- ============================================================
-- RLS — trails
-- ============================================================

-- SELECT
create policy "trails: public visible to all"
  on public.trails for select
  using (visibility = 'public');

create policy "trails: super_admin select all"
  on public.trails for select
  using (public.get_my_role() = 'super_admin');

create policy "trails: admin select all"
  on public.trails for select
  using (public.get_my_role() = 'admin');

create policy "trails: super_user select all"
  on public.trails for select
  using (public.get_my_role() = 'super_user');

create policy "trails: user select all"
  on public.trails for select
  using (public.get_my_role() = 'user');

-- INSERT
create policy "trails: super_admin insert"
  on public.trails for insert
  with check (public.get_my_role() = 'super_admin');

create policy "trails: admin insert local"
  on public.trails for insert
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user insert local"
  on public.trails for insert
  with check (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- UPDATE
create policy "trails: super_admin update"
  on public.trails for update
  using (public.get_my_role() = 'super_admin')
  with check (public.get_my_role() = 'super_admin');

create policy "trails: admin update local"
  on public.trails for update
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user update local"
  on public.trails for update
  using (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- DELETE
create policy "trails: super_admin delete"
  on public.trails for delete
  using (public.get_my_role() = 'super_admin');

create policy "trails: admin delete local"
  on public.trails for delete
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user delete local"
  on public.trails for delete
  using (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- ============================================================
-- RPCs
-- ============================================================

-- Admin user listing
create or replace function public.get_admin_users()
returns table (
  profile_id   bigint,
  auth_user_id uuid,
  email        text,
  name         text,
  role         public.app_role,
  region_name  text,
  phone        text,
  bio          text,
  created_at   timestamptz
)
language sql
security definer
stable
as $$
  select
    p.id          as profile_id,
    p.auth_user_id::uuid,
    u.email::text,
    p.name,
    p.role,
    r.name        as region_name,
    p.phone,
    p.bio,
    p.created_at
  from public.profiles p
  join auth.users u on u.id = p.auth_user_id::uuid
  join public.regions r on r.id = p.region_id
  where public.is_admin()
  order by p.created_at desc;
$$;

revoke execute on function public.get_admin_users() from public;
grant execute on function public.get_admin_users() to authenticated;

-- Trail listing with GeoJSON geometry
create or replace function public.get_trails(
  hidden boolean default false
)
returns table (
  id             bigint,
  name           text,
  type           text,
  trail_class    text,
  activity_types text[],
  direction      text,
  hidden         boolean,
  planned        boolean,
  connector      boolean,
  bike           boolean,
  tf_popularity  numeric,
  visibility     text,
  region_id      bigint,
  geometry       json
)
language sql
security invoker
stable
as $$
  select
    t.id,
    t.name,
    t.type,
    t.trail_class,
    t.activity_types,
    t.direction,
    t.hidden,
    t.planned,
    t.connector,
    t.bike,
    t.tf_popularity,
    t.visibility,
    t.region_id,
    ST_AsGeoJSON(t.geometry)::json as geometry
  from public.trails t
  where
    (get_trails.hidden or not t.hidden)
  order by t.id;
$$;

grant execute on function public.get_trails(boolean) to anon, authenticated;
