-- ============================================================
-- Migration: Role-Based Access Control with Regions
-- ============================================================
-- Replaces the boolean permissions table + user_type with:
--   - app_role enum on profiles (super_admin, admin, super_user, user)
--   - regions table with FK on profiles and trails
--   - visibility column on trails (public, private, shared)
-- Drops: permissions table, trail_attribution table, restriction column
-- ============================================================

-- ============================================================
-- 1. Create regions table
-- ============================================================
create table public.regions (
  id   bigint generated by default as identity primary key,
  name text not null unique
);

comment on table public.regions is 'Geographic regions for scoping access';

alter table public.regions enable row level security;

-- Everyone can read regions
create policy "regions: select" on public.regions for select using (true);

-- Only service_role can manage regions
create policy "regions: service_role manage" on public.regions for all
  using (auth.role() = 'service_role');

grant select on public.regions to anon, authenticated;
grant all on public.regions to service_role;
grant all on sequence public.regions_id_seq to service_role;


-- ============================================================
-- 2. Create app_role enum
-- ============================================================
create type public.app_role as enum ('super_admin', 'admin', 'super_user', 'user');

-- ============================================================
-- 3. Alter profiles: drop user_type, add role + region_id
-- ============================================================
alter table public.profiles
  add column role public.app_role not null default 'user';

alter table public.profiles
  add column region_id bigint references public.regions (id);

-- Migrate existing data: admins become admin role, others become user
update public.profiles set role = 'admin'
  where id in (select profile_id from public.permissions where is_admin = true);

update public.profiles set role = 'user'
  where role = 'user' and id not in (select profile_id from public.permissions where is_admin = true);

-- Set all existing profiles to the default region
update public.profiles set region_id = 1;

-- Now make region_id NOT NULL
alter table public.profiles alter column region_id set not null;

-- Drop old user_type column
alter table public.profiles drop column user_type;

-- ============================================================
-- 4. Alter trails: drop restriction, add visibility + region_id
-- ============================================================

-- Must drop old policies before dropping the restriction column they reference
drop policy if exists "trails: select" on public.trails;
drop policy if exists "trails: admins insert" on public.trails;
drop policy if exists "trails: admins update" on public.trails;
drop policy if exists "trails: admins delete" on public.trails;

alter table public.trails
  add column visibility text not null default 'public'
    check (visibility in ('public', 'private', 'shared'));

alter table public.trails
  add column region_id bigint references public.regions (id);

-- Migrate existing data: all existing trails become public
-- (restriction was already 'public' for most, and we're dropping attribution)
update public.trails set visibility = 'public';

-- Set all existing trails to the default region
update public.trails set region_id = 1;

-- Now make region_id NOT NULL
alter table public.trails alter column region_id set not null;

-- Drop old restriction column
alter table public.trails drop column restriction;

-- ============================================================
-- 5. Drop trail_attribution table and its helper function
-- ============================================================
-- Drop policies first
drop policy if exists "trail_attribution: select" on public.trail_attribution;
drop policy if exists "trail_attribution: admins insert" on public.trail_attribution;
drop policy if exists "trail_attribution: admins update" on public.trail_attribution;
drop policy if exists "trail_attribution: admins delete" on public.trail_attribution;

drop table public.trail_attribution;
drop function if exists public.is_attributed_to_trail(bigint);

-- ============================================================
-- 6. Drop permissions table and related objects
-- ============================================================
-- Drop policies
drop policy if exists "Users can view own permissions" on public.permissions;
drop policy if exists "Admins can manage all permissions" on public.permissions;
drop policy if exists "permissions: authenticated cannot insert" on public.permissions;
drop policy if exists "permissions: authenticated cannot update" on public.permissions;
drop policy if exists "permissions: authenticated cannot delete" on public.permissions;

-- Drop trigger + trigger function
drop trigger if exists on_profile_created on public.profiles;
drop function if exists public.handle_new_profile();
drop trigger if exists permissions_set_updated_at on public.permissions;

drop table public.permissions;

-- ============================================================
-- 7. Rewrite is_admin() to use role enum
-- ============================================================
create or replace function public.is_admin()
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.profiles
    where auth_user_id = auth.uid()
      and role in ('super_admin', 'admin')
  );
$$;

-- ============================================================
-- 8. New helper: get the calling user's role
-- ============================================================
create or replace function public.get_my_role()
returns public.app_role language sql security definer stable as $$
  select role from public.profiles
  where auth_user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.get_my_role() to authenticated;

-- ============================================================
-- 9. New helper: get the calling user's region_id
-- ============================================================
create or replace function public.get_my_region_id()
returns bigint language sql security definer stable as $$
  select region_id from public.profiles
  where auth_user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.get_my_region_id() to authenticated;

-- ============================================================
-- 10. Rewrite RLS policies on profiles
-- ============================================================
-- Drop old policies
drop policy if exists "profiles: users can view own profile" on public.profiles;
drop policy if exists "profiles: admins can view all profiles" on public.profiles;
drop policy if exists "profiles: admins can insert profiles" on public.profiles;
drop policy if exists "profiles: users can update own profile" on public.profiles;
drop policy if exists "profiles: admins can update any profile" on public.profiles;
drop policy if exists "profiles: admins can delete profiles" on public.profiles;

-- SELECT: users see own profile; admin/super_admin see all in their region; super_admin sees all
create policy "profiles: select own"
  on public.profiles for select
  using (auth_user_id = auth.uid());

create policy "profiles: super_admin select all"
  on public.profiles for select
  using (public.get_my_role() = 'super_admin');

create policy "profiles: admin select local"
  on public.profiles for select
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- INSERT: super_admin anywhere, admin in their region
create policy "profiles: super_admin insert"
  on public.profiles for insert
  with check (public.get_my_role() = 'super_admin');

create policy "profiles: admin insert local"
  on public.profiles for insert
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- UPDATE: own profile, super_admin any, admin local
create policy "profiles: update own"
  on public.profiles for update
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

create policy "profiles: super_admin update any"
  on public.profiles for update
  using (public.get_my_role() = 'super_admin')
  with check (public.get_my_role() = 'super_admin');

create policy "profiles: admin update local"
  on public.profiles for update
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- DELETE: super_admin any, admin local
create policy "profiles: super_admin delete"
  on public.profiles for delete
  using (public.get_my_role() = 'super_admin');

create policy "profiles: admin delete local"
  on public.profiles for delete
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

-- ============================================================
-- 11. Rewrite RLS policies on trails
-- ============================================================
-- (Old policies already dropped in section 4 before dropping restriction column)

-- SELECT:
--   super_admin: all trails everywhere
--   admin: all trails (read all, manage local)
--   super_user/user: all public trails + private/shared in their region
--   anon: public trails in their region (no region = all public? or none?)
--     → anon sees public trails only (no region context for anon)

create policy "trails: public visible to all"
  on public.trails for select
  using (visibility = 'public');

create policy "trails: super_admin select all"
  on public.trails for select
  using (public.get_my_role() = 'super_admin');

create policy "trails: admin select all"
  on public.trails for select
  using (public.get_my_role() = 'admin');

create policy "trails: super_user select all"
  on public.trails for select
  using (public.get_my_role() = 'super_user');

create policy "trails: user select all"
  on public.trails for select
  using (public.get_my_role() = 'user');

-- INSERT: super_admin anywhere, admin/super_user local only
create policy "trails: super_admin insert"
  on public.trails for insert
  with check (public.get_my_role() = 'super_admin');

create policy "trails: admin insert local"
  on public.trails for insert
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user insert local"
  on public.trails for insert
  with check (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- UPDATE: super_admin anywhere, admin/super_user local only
create policy "trails: super_admin update"
  on public.trails for update
  using (public.get_my_role() = 'super_admin')
  with check (public.get_my_role() = 'super_admin');

create policy "trails: admin update local"
  on public.trails for update
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user update local"
  on public.trails for update
  using (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  )
  with check (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- DELETE: super_admin anywhere, admin/super_user local only
create policy "trails: super_admin delete"
  on public.trails for delete
  using (public.get_my_role() = 'super_admin');

create policy "trails: admin delete local"
  on public.trails for delete
  using (
    public.get_my_role() = 'admin'
    and region_id = public.get_my_region_id()
  );

create policy "trails: super_user delete local"
  on public.trails for delete
  using (
    public.get_my_role() = 'super_user'
    and region_id = public.get_my_region_id()
  );

-- ============================================================
-- 12. Rewrite get_admin_users() RPC
-- ============================================================
drop function if exists public.get_admin_users();
create or replace function public.get_admin_users()
returns table (
  profile_id   bigint,
  auth_user_id uuid,
  email        text,
  name         text,
  role         public.app_role,
  region_name  text,
  phone        text,
  bio          text,
  created_at   timestamptz
)
language sql
security definer
stable
as $$
  select
    p.id          as profile_id,
    p.auth_user_id::uuid,
    u.email::text,
    p.name,
    p.role,
    r.name        as region_name,
    p.phone,
    p.bio,
    p.created_at
  from public.profiles p
  join auth.users u on u.id = p.auth_user_id::uuid
  join public.regions r on r.id = p.region_id
  where public.is_admin()
  order by p.created_at desc;
$$;

revoke execute on function public.get_admin_users() from public;
grant execute on function public.get_admin_users() to authenticated;

-- ============================================================
-- 13. Rewrite get_trails() RPC
-- ============================================================
drop function if exists public.get_trails(boolean);
create or replace function public.get_trails(
  hidden boolean default false
)
returns table (
  id             bigint,
  name           text,
  type           text,
  trail_class    text,
  activity_types text[],
  direction      text,
  hidden         boolean,
  planned        boolean,
  connector      boolean,
  bike           boolean,
  tf_popularity  numeric,
  visibility     text,
  region_id      bigint,
  geometry       json
)
language sql
security invoker
stable
as $$
  select
    t.id,
    t.name,
    t.type,
    t.trail_class,
    t.activity_types,
    t.direction,
    t.hidden,
    t.planned,
    t.connector,
    t.bike,
    t.tf_popularity,
    t.visibility,
    t.region_id,
    ST_AsGeoJSON(t.geometry)::json as geometry
  from public.trails t
  where
    (get_trails.hidden or not t.hidden)
  order by t.id;
$$;

grant execute on function public.get_trails(boolean) to anon, authenticated;
