create table public.general_geom_collection (
  id          bigint generated by default as identity primary key,
  added_by    bigint references public.profiles (id) on delete set null,
  label       text not null,
  description text,
  style       jsonb not null default '{}'::jsonb,
  visibility  text not null default 'public'
               check (visibility in ('public', 'private', 'shared')),
  region_id   bigint not null references public.regions (id) on delete cascade,
  geom_type   text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz default null
);

create table public.general_geom (
  id            bigint generated by default as identity primary key,
  collection_id bigint not null references public.general_geom_collection (id) on delete cascade,
  type          text not null,
  subtype       text,
  visibility    text not null default 'public'
                 check (visibility in ('public', 'private', 'shared')),
  label         text not null,
  description   text,
  geometry      geometry(Geometry, 4326) not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz default null
);

create index general_geom_collection_region_idx on public.general_geom_collection (region_id);
create index general_geom_collection_geom_type_idx on public.general_geom_collection (geom_type);
create index general_geom_collection_deleted_at_idx on public.general_geom_collection (deleted_at);
create index general_geom_collection_visibility_idx on public.general_geom_collection (visibility);
create index general_geom_collection_added_by_idx on public.general_geom_collection (added_by);

create index general_geom_collection_geom_idx on public.general_geom (collection_id);
create index general_geom_deleted_at_idx on public.general_geom (deleted_at);
create index general_geom_visibility_idx on public.general_geom (visibility);
create index general_geom_geometry_idx on public.general_geom using gist (geometry);

create trigger general_geom_collection_set_updated_at
  before update on public.general_geom_collection
  for each row execute function public.set_updated_at();

create trigger general_geom_set_updated_at
  before update on public.general_geom
  for each row execute function public.set_updated_at();

alter table public.general_geom_collection enable row level security;
alter table public.general_geom enable row level security;

grant select on public.general_geom_collection to anon, authenticated;
grant insert on public.general_geom_collection to authenticated;
grant update (
  label,
  description,
  style,
  visibility,
  region_id,
  geom_type,
  deleted_at,
  updated_at
) on public.general_geom_collection to authenticated;
grant delete on public.general_geom_collection to authenticated;
grant all on public.general_geom_collection to service_role;
grant all on sequence public.general_geom_collection_id_seq to service_role;

grant select on public.general_geom to anon, authenticated;
grant insert on public.general_geom to authenticated;
grant update (
  collection_id,
  type,
  subtype,
  visibility,
  label,
  description,
  geometry,
  deleted_at,
  updated_at
) on public.general_geom to authenticated;
grant delete on public.general_geom to authenticated;
grant all on public.general_geom to service_role;
grant all on sequence public.general_geom_id_seq to service_role;

create policy "general_geom_collection: select"
  on public.general_geom_collection for select
  using (
    (deleted_at is null and visibility = 'public')
    or (select auth.role()) = 'authenticated'
  );

create policy "general_geom_collection: insert"
  on public.general_geom_collection as permissive for insert
  to authenticated
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom_collection: update"
  on public.general_geom_collection as permissive for update
  to authenticated
  using (public.assert_data_write_permission(region_id) = true)
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom_collection: delete"
  on public.general_geom_collection as permissive for delete
  to authenticated
  using (
    public.assert_data_write_permission(region_id) = true
    and (select auth.jwt()) ->> 'user_role' = 'super_admin'
  );

create policy "general_geom: select"
  on public.general_geom for select
  using (
    deleted_at is null
    and exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and (
          (c.visibility = 'public' and visibility = 'public')
          or (select auth.role()) = 'authenticated'
        )
    )
  );

create policy "general_geom: insert"
  on public.general_geom as permissive for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and public.assert_data_write_permission(c.region_id) = true
    )
  );

create policy "general_geom: update"
  on public.general_geom as permissive for update
  to authenticated
  using (
    exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and public.assert_data_write_permission(c.region_id) = true
    )
  )
  with check (
    exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and public.assert_data_write_permission(c.region_id) = true
    )
  );

create policy "general_geom: delete"
  on public.general_geom as permissive for delete
  to authenticated
  using (
    exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and public.assert_data_write_permission(c.region_id) = true
    )
    and (select auth.jwt()) ->> 'user_role' = 'super_admin'
  );

create view public.general_geom_view
  with (security_invoker = true)
as
select
  g.id,
  g.collection_id,
  c.label as collection_label,
  c.geom_type,
  c.region_id,
  c.visibility as collection_visibility,
  g.type,
  g.subtype,
  g.visibility,
  g.label,
  g.description,
  g.created_at,
  g.updated_at,
  g.deleted_at,
  st_asgeojson(g.geometry)::json as geometry_geojson,
  replace(st_geometrytype(g.geometry), 'ST_', '') as geometry_type
from public.general_geom g
join public.general_geom_collection c on c.id = g.collection_id
where g.deleted_at is null
  and c.deleted_at is null;

grant select on public.general_geom_view to anon, authenticated;

create or replace function public.import_general_geom_collection(
  p_collection jsonb,
  p_mapper jsonb,
  p_features jsonb,
  p_source_epsg integer default 4326
)
returns table (
  ok      boolean,
  id      bigint,
  message text
)
language sql
security invoker
set search_path = ''
as $$
  with collection_insert as (
    insert into public.general_geom_collection (
      added_by,
      label,
      description,
      style,
      visibility,
      region_id,
      geom_type
    )
    values (
      (
        select p.id
        from public.profiles p
        where p.auth_user_id = auth.uid()
          and p.deleted_at is null
        limit 1
      ),
      coalesce(nullif(p_collection ->> 'label', ''), 'Imported geometry'),
      nullif(p_collection ->> 'description', ''),
      coalesce(p_collection -> 'style', '{}'::jsonb),
      coalesce(nullif(p_collection ->> 'visibility', ''), 'public'),
      (p_collection ->> 'region_id')::bigint,
      coalesce(nullif(p_collection ->> 'geom_type', ''), 'Geometry')
    )
    returning id
  ),
  parsed as (
    select
      f.feat,
      f.ord,
      coalesce(f.feat -> 'properties', '{}'::jsonb) as props,
      public.st_force2d(
        case
          when coalesce(p_source_epsg, 4326) = 4326 then
            public.st_setsrid(
              public.st_geomfromgeojson((f.feat -> 'geometry')::text),
              4326
            )
          else
            public.st_transform(
              public.st_setsrid(
                public.st_geomfromgeojson((f.feat -> 'geometry')::text),
                coalesce(p_source_epsg, 4326)
              ),
              4326
            )
        end
      ) as geom
    from jsonb_array_elements(p_features) with ordinality as f(feat, ord)
  ),
  inserted as (
    insert into public.general_geom (
      collection_id,
      type,
      subtype,
      visibility,
      label,
      description,
      geometry
    )
    select
      c.id,
      coalesce(
        nullif(trim(parsed.props ->> nullif(p_mapper #>> '{type,field}', '')), ''),
        nullif(trim(p_mapper #>> '{type,fallback}'), ''),
        'feature'
      ),
      coalesce(
        nullif(trim(parsed.props ->> nullif(p_mapper #>> '{subtype,field}', '')), ''),
        nullif(trim(p_mapper #>> '{subtype,fallback}'), '')
      ),
      coalesce(
        nullif(trim(parsed.props ->> nullif(p_mapper #>> '{visibility,field}', '')), ''),
        nullif(trim(p_mapper #>> '{visibility,fallback}'), ''),
        'public'
      ),
      coalesce(
        nullif(trim(parsed.props ->> nullif(p_mapper #>> '{label,field}', '')), ''),
        nullif(trim(p_mapper #>> '{label,fallback}'), ''),
        concat(
          coalesce(nullif(p_mapper #>> '{label,auto_increment_suffix}', ''), 'Feature '),
          parsed.ord::text
        )
      ),
      case
        when coalesce((p_mapper #>> '{description,include_props_json}')::boolean, false)
        then concat_ws(
          E'\n',
          coalesce(
            nullif(trim(parsed.props ->> nullif(p_mapper #>> '{description,field}', '')), ''),
            nullif(trim(p_mapper #>> '{description,fallback}'), '')
          ),
          parsed.props::text
        )
        else coalesce(
          nullif(trim(parsed.props ->> nullif(p_mapper #>> '{description,field}', '')), ''),
          nullif(trim(p_mapper #>> '{description,fallback}'), '')
        )
      end,
      parsed.geom
    from parsed
    cross join collection_insert c
    where parsed.geom is not null
    returning id
  )
  select true, inserted.id, null::text from inserted;
$$;

revoke execute on function public.import_general_geom_collection(jsonb, jsonb, jsonb, integer) from public;
grant execute on function public.import_general_geom_collection(jsonb, jsonb, jsonb, integer) to authenticated;
