-- Supabase's local init sets DEFAULT PRIVILEGES that individually grant EXECUTE
-- on all public-schema functions to anon/authenticated/service_role. A plain
-- REVOKE ALL FROM PUBLIC (as generated by supabase db diff) does not remove
-- those per-role grants. Explicitly revoke anon from RPCs that must be
-- restricted to authenticated or service_role callers only.

REVOKE ALL ON FUNCTION "public"."get_admin_users"() FROM anon;
REVOKE ALL ON FUNCTION "public"."get_rls_policies"() FROM anon;
REVOKE ALL ON FUNCTION "public"."get_rpc_privileges"() FROM anon;
REVOKE ALL ON FUNCTION "public"."get_soft_delete_perms"() FROM anon;
REVOKE ALL ON FUNCTION "public"."assert_data_write_permission"(bigint) FROM anon;
REVOKE ALL ON FUNCTION "public"."change_user_role"(bigint, "public"."app_role") FROM anon;
REVOKE ALL ON FUNCTION "public"."custom_access_token_hook"(jsonb) FROM anon;
