-- Permissions table
-- One row per profile. Boolean flags for each permission level.
-- Admin implies all other permissions.

create table "public"."permissions" (
  "id"         bigint generated by default as identity primary key,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "profile_id" bigint not null references "public"."profiles" ("id") on delete cascade,
  "can_read"   boolean not null default true,
  "can_write"  boolean not null default false,
  "can_delete" boolean not null default false,
  "is_admin"   boolean not null default false,
  constraint "permissions_profile_id_key" unique ("profile_id")
);

comment on table  "public"."permissions"            is 'Per-profile permission flags';
comment on column "public"."permissions"."can_read"  is 'Can read/view content';
comment on column "public"."permissions"."can_write" is 'Can create and edit content';
comment on column "public"."permissions"."can_delete" is 'Can delete content';
comment on column "public"."permissions"."is_admin"  is 'Full admin access — implies all other permissions';

-- Keep updated_at current automatically
create function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger permissions_set_updated_at
  before update on "public"."permissions"
  for each row execute function public.set_updated_at();

-- Auto-create a default permissions row whenever a profile is created
create function public.handle_new_profile()
returns trigger language plpgsql security definer
set search_path = ''
as $$
begin
  insert into public.permissions (profile_id)
  values (new.id);
  return new;
end;
$$;

create trigger on_profile_created
  after insert on "public"."profiles"
  for each row execute function public.handle_new_profile();

-- RLS
alter table "public"."permissions" enable row level security;

-- Users can read their own permissions
create policy "Users can view own permissions"
  on "public"."permissions" for select
  using (
    profile_id in (
      select id from public.profiles where auth_user_id = auth.uid()
    )
  );

-- Only admins (via service_role or an admin policy) can modify permissions
create policy "Admins can manage all permissions"
  on "public"."permissions" for all
  using (auth.role() = 'service_role');

-- Grants
grant select on table "public"."permissions" to "authenticated";
grant all    on table "public"."permissions" to "service_role";
grant all    on sequence "public"."permissions_id_seq" to "service_role";
