-- The auto_attach_block_deleted_at event trigger fires on CREATE TABLE and
-- would create the block_deleted_at trigger automatically. Disable it so we
-- can create the triggers manually with explicit args below.

alter event trigger auto_attach_block_deleted_at disable;

create table public.general_geom_collection (
  id          bigint generated by default as identity primary key,
  added_by    bigint references public.profiles (id) on delete set null,
  label       text not null,
  description text,
  style       jsonb not null default '{}'::jsonb,
  visibility  text not null default 'public'
               check (visibility in ('public', 'private', 'shared')),
  region_id   bigint not null references public.regions (id) on delete cascade,
  feature_collection_type text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz default null
);

create table public.general_geom (
  id            bigint generated by default as identity primary key,
  collection_id bigint not null references public.general_geom_collection (id) on delete cascade,
  region_id     bigint not null references public.regions (id) on delete restrict,
  type          text not null,
  subtype       text,
  visibility    text not null default 'public'
                 check (visibility in ('public', 'private', 'shared')),
  label         text not null,
  description   text,
  geometry      geometry(Geometry, 4326) not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz default null
);

create trigger general_geom_collection_block_deleted_at
  before update on public.general_geom_collection
  for each row execute function public.block_deleted_at_update('REGION', 'REGION', 'NONE');

create trigger general_geom_block_deleted_at
  before update on public.general_geom
  for each row execute function public.block_deleted_at_update('REGION', 'REGION', 'NONE');

create index general_geom_collection_region_idx on public.general_geom_collection (region_id);
create index general_geom_collection_feature_collection_type_idx on public.general_geom_collection (feature_collection_type);
create index general_geom_collection_deleted_at_idx on public.general_geom_collection (deleted_at);
create index general_geom_collection_visibility_idx on public.general_geom_collection (visibility);
create index general_geom_collection_added_by_idx on public.general_geom_collection (added_by);

create index general_geom_collection_geom_idx on public.general_geom (collection_id);
create index general_geom_deleted_at_idx on public.general_geom (deleted_at);
create index general_geom_visibility_idx on public.general_geom (visibility);
create index general_geom_region_id_idx on public.general_geom (region_id);
create index general_geom_geometry_idx on public.general_geom using gist (geometry);

create trigger general_geom_collection_set_updated_at
  before update on public.general_geom_collection
  for each row execute function public.set_updated_at();

create trigger general_geom_set_updated_at
  before update on public.general_geom
  for each row execute function public.set_updated_at();

alter table public.general_geom_collection enable row level security;
alter table public.general_geom enable row level security;

grant select on public.general_geom_collection to anon, authenticated;
grant insert on public.general_geom_collection to authenticated;
grant update (
  label,
  description,
  style,
  visibility,
  region_id,
  feature_collection_type,
  deleted_at,
  updated_at
) on public.general_geom_collection to authenticated;
grant delete on public.general_geom_collection to authenticated;
grant all on public.general_geom_collection to service_role;
grant all on sequence public.general_geom_collection_id_seq to service_role;

grant select on public.general_geom to anon, authenticated;
grant insert on public.general_geom to authenticated;
grant update (
  collection_id,
  region_id,
  type,
  subtype,
  visibility,
  label,
  description,
  geometry,
  deleted_at,
  updated_at
) on public.general_geom to authenticated;
grant delete on public.general_geom to authenticated;
grant all on public.general_geom to service_role;
grant all on sequence public.general_geom_id_seq to service_role;

-- ── RLS policies ─────────────────────────────────────────────────────────────

create policy "general_geom_collection: select"
  on public.general_geom_collection for select
  using (
    (deleted_at is null and visibility = 'public')
    or (select auth.role()) = 'authenticated'
  );

create policy "general_geom_collection: insert"
  on public.general_geom_collection as permissive for insert
  to authenticated
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom_collection: update"
  on public.general_geom_collection as permissive for update
  to authenticated
  using (public.assert_data_write_permission(region_id) = true)
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom_collection: delete"
  on public.general_geom_collection as permissive for delete
  to authenticated
  using (
    public.assert_data_write_permission(region_id) = true
    and (select auth.jwt()) ->> 'user_role' = 'super_admin'
  );

-- general_geom has its own region_id — same pattern as trails.
create policy "general_geom: select"
  on public.general_geom for select
  using (
    deleted_at is null
    and exists (
      select 1
      from public.general_geom_collection c
      where c.id = collection_id
        and c.deleted_at is null
        and (
          (c.visibility = 'public' and visibility = 'public')
          or (select auth.role()) = 'authenticated'
        )
    )
  );

create policy "general_geom: insert"
  on public.general_geom as permissive for insert
  to authenticated
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom: update"
  on public.general_geom as permissive for update
  to authenticated
  using (public.assert_data_write_permission(region_id) = true)
  with check (public.assert_data_write_permission(region_id) = true);

create policy "general_geom: delete"
  on public.general_geom as permissive for delete
  to authenticated
  using (
    public.assert_data_write_permission(region_id) = true
    and (select auth.jwt()) ->> 'user_role' = 'super_admin'
  );

-- ── View ─────────────────────────────────────────────────────────────────────

create view public.general_geom_view
  with (security_invoker = true)
as
select
  g.id,
  g.collection_id,
  c.label as collection_label,
  c.feature_collection_type,
  c.region_id,
  c.visibility as collection_visibility,
  g.type,
  g.subtype,
  g.visibility,
  g.label,
  g.description,
  g.created_at,
  g.updated_at,
  g.deleted_at,
  st_asgeojson(g.geometry)::json as geometry_geojson,
  replace(st_geometrytype(g.geometry), 'ST_', '') as geometry_type
from public.general_geom g
join public.general_geom_collection c on c.id = g.collection_id
where g.deleted_at is null
  and c.deleted_at is null;

grant select on public.general_geom_view to anon, authenticated;

-- ── Import function ──────────────────────────────────────────────────────────
-- Uses plpgsql with two separate statements so that the general_geom INSERT
-- runs after the collection row is committed to the table, avoiding a
-- PostgreSQL quirk where RLS policy evaluation inside a data-modifying CTE
-- cannot see auth context correctly.

create or replace function public.import_general_geom_collection(
  p_collection jsonb,
  p_features jsonb,
  p_source_epsg integer default 4326
)
returns table (
  ok      boolean,
  id      bigint,
  message text
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_region_id     bigint;
  v_collection_id bigint;
begin
  -- Resolve region_id from the arg or fall back to caller's profile.
  v_region_id := coalesce(
    (p_collection ->> 'region_id')::bigint,
    (
      select p.region_id
      from public.profiles p
      where p.auth_user_id = auth.uid()
        and p.deleted_at is null
      limit 1
    )
  );

  -- 1) Insert the collection.
  insert into public.general_geom_collection (
    added_by, label, description, style, visibility, region_id, feature_collection_type
  )
  values (
    (
      select p.id from public.profiles p
      where p.auth_user_id = auth.uid() and p.deleted_at is null
      limit 1
    ),
    coalesce(nullif(p_collection ->> 'label', ''), 'Imported geometry'),
    nullif(p_collection ->> 'description', ''),
    coalesce(p_collection -> 'style', '{}'::jsonb),
    coalesce(nullif(p_collection ->> 'visibility', ''), 'public'),
    v_region_id,
    coalesce(nullif(p_collection ->> 'feature_collection_type', ''), 'Geometry')
  )
  returning general_geom_collection.id into v_collection_id;

  -- 2) Insert the features.
  return query
    insert into public.general_geom (
      collection_id, region_id, type, subtype, visibility,
      label, description, geometry
    )
    select
      v_collection_id,
      v_region_id,
      coalesce(nullif(trim(props ->> 'type'),       ''), 'feature'),
      nullif(trim(props ->> 'subtype'), ''),
      coalesce(nullif(trim(props ->> 'visibility'), ''), 'public'),
      coalesce(nullif(trim(props ->> 'label'),      ''), 'Unnamed'),
      nullif(trim(props ->> 'description'), ''),
      public.st_force2d(
        case
          when coalesce(p_source_epsg, 4326) = 4326 then
            public.st_setsrid(
              public.st_geomfromgeojson((f.feat -> 'geometry')::text),
              4326
            )
          else
            public.st_transform(
              public.st_setsrid(
                public.st_geomfromgeojson((f.feat -> 'geometry')::text),
                coalesce(p_source_epsg, 4326)
              ),
              4326
            )
        end
      )
    from jsonb_array_elements(p_features) as f(feat),
         lateral (select coalesce(f.feat -> 'properties', '{}'::jsonb)) as p(props)
    where f.feat -> 'geometry' is not null
    returning true, general_geom.id, null::text;
end;
$$;

revoke execute on function public.import_general_geom_collection(jsonb, jsonb, integer) from public;
grant execute on function public.import_general_geom_collection(jsonb, jsonb, integer) to authenticated;

alter event trigger auto_attach_block_deleted_at enable;
