-- Trail elevation: adds geom_updated_at to trails and creates the trail_elevations table.
-- The Python elevation app (elevation/) reads geom_updated_at to detect stale profiles
-- and writes computed 3D geometry + elevation profiles into trail_elevations.

-- ── 1. Add geom_updated_at to trails ─────────────────────────────────────────
-- Records when the geometry column was last changed. Initialised to updated_at
-- for existing rows; subsequently maintained by the trigger below.

alter table public.trails
  add column if not exists geom_updated_at timestamptz not null default now();

comment on column public.trails.geom_updated_at is
  'Timestamp of the last geometry change. Maintained by trails_set_geom_updated_at trigger. '
  'Compared against trail_elevations.updated_at to detect stale elevation profiles.';

-- Back-fill existing rows from updated_at (best available proxy for when the
-- geometry was last changed; the DEFAULT above set all rows to now()).
update public.trails
  set geom_updated_at = updated_at;

-- ── 2. Trigger function: keep geom_updated_at in sync ────────────────────────

create or replace function public.set_geom_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.geometry is distinct from old.geometry then
    new.geom_updated_at = now();
  end if;
  return new;
end;
$$;

comment on function public.set_geom_updated_at() is
  'BEFORE UPDATE trigger that bumps geom_updated_at whenever the geometry column changes.';

create trigger trails_set_geom_updated_at
  before update on public.trails
  for each row execute function public.set_geom_updated_at();

-- ── 3. trail_elevations table ─────────────────────────────────────────────────

create table public.trail_elevations (
  id                bigint generated by default as identity primary key,
  trail_id          bigint not null unique references public.trails (id) on delete cascade,
  geometry_3d       geometry(LineStringZ, 4326),
  elevation_profile jsonb  not null default '[]'::jsonb,
  updated_at        timestamptz not null default now()
);

comment on table public.trail_elevations is
  '1-to-1 extension of trails. Stores the 3D LineString and the distance/elevation profile '
  'computed by the Python elevation app. Updated_at is compared with trails.geom_updated_at '
  'to detect profiles that are out of date.';

comment on column public.trail_elevations.geometry_3d is
  '3D LineString (Z = elevation in metres) in WGS84 (EPSG:4326). '
  'Densified to roughly one vertex every 5 m by the elevation app.';

comment on column public.trail_elevations.elevation_profile is
  'Ordered array of {distance_m, elevation_m} objects representing the elevation chart. '
  'distance_m is the cumulative great-circle distance along the trail in metres.';

comment on column public.trail_elevations.updated_at is
  'When the elevation data was last computed. Compared with trails.geom_updated_at to '
  'detect profiles that need a refresh (threshold: 30 seconds).';

create index trail_elevations_trail_id_idx on public.trail_elevations (trail_id);
create index trail_elevations_geometry_3d_idx on public.trail_elevations using gist (geometry_3d);

-- ── 4. RLS ────────────────────────────────────────────────────────────────────

alter table public.trail_elevations enable row level security;

create policy "trail_elevations: select"
  on public.trail_elevations for select
  using (true);

-- ── 5. Grants ─────────────────────────────────────────────────────────────────

grant select on public.trail_elevations to anon, authenticated;
grant all    on public.trail_elevations to service_role;
grant all    on sequence public.trail_elevations_id_seq to service_role;
