-- Squashed initial schema. See supabase/ARCHITECTURE.md for design notes.

create extension if not exists postgis;

create type public.app_role as enum (
  'pending',
  'user',
  'super_user',
  'admin',
  'super_admin'
);

create or replace function public.set_updated_at()
returns trigger language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.regions (
  id   bigint generated by default as identity primary key,
  name text not null unique
);

comment on table public.regions is 'Geographic regions for scoping access';

insert into public.regions (id, name) values (0, 'Default') on conflict (id) do nothing;

alter table public.regions enable row level security;

create policy "regions: select"
  on public.regions for select
  using (true);

create policy "regions: super_admin insert"
  on public.regions for insert
  with check ((select auth.jwt() ->> 'user_role') = 'super_admin');

create policy "regions: super_admin update"
  on public.regions for update
  using  ((select auth.jwt() ->> 'user_role') = 'super_admin')
  with check ((select auth.jwt() ->> 'user_role') = 'super_admin');

create policy "regions: super_admin delete"
  on public.regions for delete
  using  ((select auth.jwt() ->> 'user_role') = 'super_admin');

grant select on public.regions to anon, authenticated;
grant all on public.regions to service_role;
grant all on sequence public.regions_id_seq to service_role;

create table public.profiles (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  auth_user_id uuid        not null,
  name         text        not null,
  role         public.app_role not null default 'user',
  region_id    bigint not null references public.regions (id),
  phone        text,
  bio          text,
  deleted_at   timestamptz default null
);

comment on column public.profiles.deleted_at is
  'Soft-delete timestamp. NULL = active. Set via soft_delete_profiles RPC only.';

create unique index profiles_name_key on public.profiles using btree (name);
alter table public.profiles add constraint "profiles_name_key"
  unique using index "profiles_name_key";

alter table public.profiles add constraint "profiles_auth_user_id_fkey"
  foreign key (auth_user_id) references auth.users(id) on delete cascade not valid;
alter table public.profiles validate constraint "profiles_auth_user_id_fkey";

alter table public.profiles enable row level security;

grant select on public.profiles to anon;
grant select, insert on public.profiles to authenticated;
grant update (name, role, region_id, phone, bio) on public.profiles to authenticated;
grant all on public.profiles to service_role;
grant all on sequence public.profiles_id_seq to service_role;

create policy "profiles: select"
  on public.profiles for select
  using (
    (select auth.jwt() ->> 'user_role') not in ('pending', 'anon')
    and (
      auth_user_id = (select auth.uid())
      or (select auth.jwt() ->> 'user_role') = 'super_admin'
      or (
        (select auth.jwt() ->> 'user_role') = 'admin'
        and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
      )
    )
  );

create policy "profiles: insert"
  on public.profiles for insert
  with check (
    (select auth.jwt() ->> 'user_role') in ('super_admin', 'admin')
    and (
      (select auth.jwt() ->> 'user_role') = 'super_admin'
      or region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  );

create policy "profiles: update"
  on public.profiles for update
  using (
    auth_user_id = (select auth.uid())
    or (select auth.jwt() ->> 'user_role') = 'super_admin'
    or (
      (select auth.jwt() ->> 'user_role') = 'admin'
      and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  )
  with check (
    auth_user_id = (select auth.uid())
    or (select auth.jwt() ->> 'user_role') = 'super_admin'
    or (
      (select auth.jwt() ->> 'user_role') = 'admin'
      and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  );

create policy "profiles: super_admin delete"
  on public.profiles for delete
  using ((select auth.jwt() ->> 'user_role') = 'super_admin');

create table public.trails (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  name           text    not null,
  description    text,
  type           text    not null,
  trail_class    text,
  activity_types text[],
  direction      text,

  hidden         boolean not null default false,
  planned        boolean not null default false,
  connector      boolean not null default false,
  bike           boolean not null default false,

  tf_popularity  numeric,

  visibility     text not null default 'public'
                   check (visibility in ('public', 'private', 'shared')),

  region_id      bigint not null references public.regions (id),

  geometry       geometry(LineString, 4326) not null,

  deleted_at     timestamptz default null
);

comment on table  public.trails              is 'Trail network segments';
comment on column public.trails.description  is 'Optional human-readable description of the trail segment';
comment on column public.trails.type         is 'Trail surface/type classification';
comment on column public.trails.trail_class  is 'Difficulty class (TC1–TC5)';
comment on column public.trails.activity_types is 'Supported activities e.g. hiking, mtb';
comment on column public.trails.direction    is 'Travel direction: both | oneway | oneway-reverse';
comment on column public.trails.hidden       is 'Hidden from public view';
comment on column public.trails.planned      is 'Planned/proposed trail, not yet built';
comment on column public.trails.connector    is 'Connector segment between main trails';
comment on column public.trails.bike         is 'Bikeable segment';
comment on column public.trails.tf_popularity is 'Trailforks popularity score';
comment on column public.trails.visibility   is 'public | private | shared';
comment on column public.trails.geometry     is 'LineString geometry in WGS84 (EPSG:4326)';
comment on column public.trails.deleted_at   is
  'Soft-delete timestamp. Non-null rows are excluded from trails_view.';

create index trails_geometry_idx on public.trails using gist (geometry);

create trigger trails_set_updated_at
  before update on public.trails
  for each row execute function public.set_updated_at();

alter table public.trails enable row level security;

grant select on public.trails to anon, authenticated;
grant insert on public.trails to authenticated;
grant update (
  name, description, type, trail_class, activity_types,
  direction, hidden, planned, connector, bike,
  tf_popularity, visibility, region_id, geometry, updated_at
) on public.trails to authenticated;
grant all on public.trails to service_role;
grant all on sequence public.trails_id_seq to service_role;

create policy "trails: select"
  on public.trails for select
  using (
    (deleted_at is null and visibility = 'public')
    or (select auth.role()) = 'authenticated'
  );

create policy "trails: insert"
  on public.trails for insert
  with check (
    (select auth.jwt() ->> 'user_role') = 'super_admin'
    or (
      (select auth.jwt() ->> 'user_role') in ('admin', 'super_user')
      and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  );

create policy "trails: update"
  on public.trails for update
  using (
    (select auth.jwt() ->> 'user_role') = 'super_admin'
    or (
      (select auth.jwt() ->> 'user_role') in ('admin', 'super_user')
      and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  )
  with check (
    (select auth.jwt() ->> 'user_role') = 'super_admin'
    or (
      (select auth.jwt() ->> 'user_role') in ('admin', 'super_user')
      and region_id = (select (auth.jwt() ->> 'region_id')::bigint)
    )
  );

create policy "trails: super_admin delete"
  on public.trails for delete
  using ((select auth.jwt() ->> 'user_role') = 'super_admin');

create view public.trails_view
  with (security_invoker = true)
as
select
  t.id,
  t.name,
  t.description,
  t.type,
  t.trail_class,
  t.activity_types,
  t.direction,
  t.hidden,
  t.planned,
  t.connector,
  t.bike,
  t.tf_popularity,
  t.visibility,
  t.region_id,
  t.created_at,
  t.updated_at,
  t.deleted_at,
  round(
    st_length(t.geometry::geography)::numeric,
    2
  )                                    as distance_m,
  st_asgeojson(t.geometry)::json       as geometry_geojson
from public.trails t
where t.deleted_at is null;

comment on view public.trails_view is
  'RLS-protected view of trails with distance_m and geometry_geojson. Excludes soft-deleted rows.';

grant select on public.trails_view to anon, authenticated;

-- Prevent direct writes to deleted_at on profiles and trails.
-- The only legitimate path is through the soft_delete_* RPCs (SECURITY DEFINER),
-- which set app.soft_delete_rpc = 'on' before updating.
create or replace function public.block_deleted_at_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.deleted_at is distinct from old.deleted_at
    and coalesce(current_setting('app.soft_delete_rpc', true), '') <> 'on'
    and current_role not in ('service_role', 'postgres', 'supabase_admin')
  then
    raise exception 'permission denied: deleted_at may only be set via the soft_delete RPC'
      using errcode = 'insufficient_privilege';
  end if;
  return new;
end;
$$;

create trigger profiles_block_deleted_at
  before update on public.profiles
  for each row execute function public.block_deleted_at_update();

create trigger trails_block_deleted_at
  before update on public.trails
  for each row execute function public.block_deleted_at_update();

create or replace function public.soft_delete_trails(ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      text   := auth.jwt() ->> 'user_role';
  v_region_id bigint := (auth.jwt() ->> 'region_id')::bigint;
begin
  if v_role = 'super_admin' then
    perform set_config('app.soft_delete_rpc', 'on', true);
    update public.trails set deleted_at = now() where id = any(ids);
    perform set_config('app.soft_delete_rpc', '', true);

  elsif v_role in ('admin', 'super_user') then
    perform set_config('app.soft_delete_rpc', 'on', true);
    update public.trails
    set deleted_at = now()
    where id = any(ids)
      and region_id = v_region_id;
    perform set_config('app.soft_delete_rpc', '', true);

    if exists (
      select 1 from public.trails
      where id = any(ids)
        and region_id <> v_region_id
        and deleted_at is null
    ) then
      raise exception 'permission denied: one or more trails are outside your region'
        using errcode = 'insufficient_privilege';
    end if;

  else
    raise exception 'permission denied: only admin, super_user, or super_admin may soft-delete trails'
      using errcode = 'insufficient_privilege';
  end if;
end;
$$;

revoke execute on function public.soft_delete_trails(bigint[]) from public;
grant  execute on function public.soft_delete_trails(bigint[]) to authenticated;

comment on function public.soft_delete_trails(bigint[]) is
  'Sets deleted_at = now() on trails. SECURITY DEFINER to bypass column-level privilege. '
  'super_admin: any trail. admin/super_user: own region only. Others: denied.';

create or replace function public.soft_delete_profiles(ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      text   := auth.jwt() ->> 'user_role';
  v_region_id bigint := (auth.jwt() ->> 'region_id')::bigint;
  v_uid       uuid   := auth.uid();
begin
  if v_uid is null then
    raise exception 'permission denied: must be authenticated'
      using errcode = 'insufficient_privilege';
  end if;

  if v_role = 'super_admin' then
    perform set_config('app.soft_delete_rpc', 'on', true);
    update public.profiles set deleted_at = now() where id = any(ids);
    perform set_config('app.soft_delete_rpc', '', true);

  elsif v_role = 'admin' then
    if exists (
      select 1 from public.profiles p
      where p.id = any(ids)
        and p.auth_user_id is distinct from v_uid
        and p.region_id is distinct from v_region_id
    ) then
      raise exception 'permission denied: you may only soft-delete profiles in your region or your own profile'
        using errcode = 'insufficient_privilege';
    end if;
    perform set_config('app.soft_delete_rpc', 'on', true);
    update public.profiles set deleted_at = now() where id = any(ids);
    perform set_config('app.soft_delete_rpc', '', true);

  else
    if exists (
      select 1 from public.profiles p
      where p.id = any(ids)
        and p.auth_user_id is distinct from v_uid
    ) then
      raise exception 'permission denied: you may only soft-delete your own profile'
        using errcode = 'insufficient_privilege';
    end if;
    perform set_config('app.soft_delete_rpc', 'on', true);
    update public.profiles set deleted_at = now() where id = any(ids);
    perform set_config('app.soft_delete_rpc', '', true);
  end if;
end;
$$;

revoke execute on function public.soft_delete_profiles(bigint[]) from public;
grant  execute on function public.soft_delete_profiles(bigint[]) to authenticated;

comment on function public.soft_delete_profiles(bigint[]) is
  'Sets deleted_at = now() on profiles. SECURITY DEFINER to bypass column-level privilege. '
  'super_admin: any. admin: own region or self. user/super_user: self only.';

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _name text;
  _role public.app_role;
begin
  if exists (select 1 from public.profiles where auth_user_id = new.id) then
    return new;
  end if;

  _name := coalesce(
    nullif(trim(new.raw_user_meta_data->>'full_name'), ''),
    nullif(trim(split_part(new.email, '@', 1)), ''),
    new.id::text
  );

  if exists (select 1 from public.profiles where name = _name) then
    _name := _name || '_' || left(new.id::text, 8);
  end if;

  if coalesce(new.raw_app_meta_data->>'provider', '') = 'email' then
    _role := 'user';
  else
    _role := 'pending';
  end if;

  insert into public.profiles (auth_user_id, name, role, region_id)
  values (new.id, _name, _role, 0);

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  claims   jsonb := coalesce(event->'claims', '{}'::jsonb);
  v_role   text;
  v_region bigint;
begin
  select p.role::text, p.region_id
    into v_role, v_region
  from public.profiles p
  where p.auth_user_id = (event->>'user_id')::uuid
    and p.deleted_at is null
  limit 1;

  claims := jsonb_set(claims, '{user_role}', to_jsonb(coalesce(v_role, 'pending')), true);
  claims := jsonb_set(claims, '{region_id}',  to_jsonb(coalesce(v_region, 0)), true);
  claims := jsonb_set(
    claims,
    '{is_admin}',
    to_jsonb(coalesce(v_role in ('admin', 'super_admin'), false)),
    true
  );

  return jsonb_set(event, '{claims}', claims, true);
end;
$$;

grant execute on function public.custom_access_token_hook(jsonb)
  to supabase_auth_admin;

revoke execute on function public.custom_access_token_hook(jsonb) from authenticated, anon, public;

create or replace function public.upsert_trails(features jsonb)
returns table (
  ok      boolean,
  id      bigint,
  message text
)
language sql
security invoker
set search_path = ''
as $$
  with parsed as (
    select
      case
        when nullif(trim((f.feat -> 'properties' ->> 'id')::text), '') is null then null
        when (f.feat -> 'properties' ->> 'id')::bigint <= 0               then null
        else (f.feat -> 'properties' ->> 'id')::bigint
      end                                                                        as trail_id,
      f.feat -> 'properties'                                                     as props,
      public.ST_SetSRID(public.ST_GeomFromGeoJSON((f.feat -> 'geometry')::text), 4326) as geom
    from jsonb_array_elements(features) as f(feat)
  ),
  updated as (
    update public.trails t
    set
      name           = coalesce(p.props ->> 'name',                    t.name),
      description    = case when p.props ? 'description'
                         then p.props ->> 'description'
                         else t.description end,
      type           = coalesce(p.props ->> 'type',                    t.type),
      trail_class    = coalesce(p.props ->> 'trail_class',             t.trail_class),
      activity_types = case when p.props ? 'activity_types'
                         then array(select jsonb_array_elements_text(p.props -> 'activity_types'))
                         else t.activity_types end,
      direction      = coalesce(p.props ->> 'direction',               t.direction),
      hidden         = coalesce((p.props ->> 'hidden')::boolean,       t.hidden),
      planned        = coalesce((p.props ->> 'planned')::boolean,      t.planned),
      connector      = coalesce((p.props ->> 'connector')::boolean,    t.connector),
      bike           = coalesce((p.props ->> 'bike')::boolean,         t.bike),
      tf_popularity  = coalesce((p.props ->> 'tf_popularity')::numeric,t.tf_popularity),
      visibility     = coalesce(p.props ->> 'visibility',              t.visibility),
      region_id      = coalesce((p.props ->> 'region_id')::bigint,     t.region_id),
      geometry       = p.geom,
      updated_at     = now()
    from parsed p
    where p.trail_id is not null
      and t.id = p.trail_id
    returning t.id
  ),
  inserted as (
    insert into public.trails (
      name, description, type, trail_class, activity_types, direction,
      hidden, planned, connector, bike, tf_popularity,
      visibility, region_id, geometry
    )
    select
      p.props ->> 'name',
      p.props ->> 'description',
      coalesce(p.props ->> 'type', 'trail'),
      p.props ->> 'trail_class',
      case when p.props ? 'activity_types'
           then array(select jsonb_array_elements_text(p.props -> 'activity_types'))
      end,
      p.props ->> 'direction',
      coalesce((p.props ->> 'hidden')::boolean,    false),
      coalesce((p.props ->> 'planned')::boolean,   false),
      coalesce((p.props ->> 'connector')::boolean, false),
      coalesce((p.props ->> 'bike')::boolean,       false),
      (p.props ->> 'tf_popularity')::numeric,
      coalesce(p.props ->> 'visibility', 'public'),
      (p.props ->> 'region_id')::bigint,
      p.geom
    from parsed p
    where p.trail_id is null
    returning trails.id
  )
  select true, id, null::text from updated
  union all
  select true, id, null::text from inserted;
$$;

revoke execute on function public.upsert_trails(jsonb) from public;
grant  execute on function public.upsert_trails(jsonb) to authenticated;

create or replace function public.get_admin_users()
returns table (
  profile_id   bigint,
  auth_user_id uuid,
  email        text,
  name         text,
  role         public.app_role,
  region_name  text,
  phone        text,
  bio          text,
  created_at   timestamptz
)
language sql
security definer
stable
set search_path = public
as $$
  select
    p.id          as profile_id,
    p.auth_user_id::uuid,
    u.email::text,
    p.name,
    p.role,
    r.name        as region_name,
    p.phone,
    p.bio,
    p.created_at
  from public.profiles p
  join auth.users u on u.id = p.auth_user_id
  join public.regions r on r.id = p.region_id
  where (auth.jwt() ->> 'user_role') in ('admin', 'super_admin')
    and p.deleted_at is null
  order by p.created_at desc;
$$;

revoke execute on function public.get_admin_users() from public, anon;
grant  execute on function public.get_admin_users() to authenticated;

create or replace function public.get_rls_policies()
returns table (
  table_name  text,
  policy_name text,
  command     text,
  roles       text,
  using_expr  text,
  check_expr  text
)
language sql
security definer
stable
set search_path = public
as $$
  select
    p.tablename::text,
    p.policyname::text,
    p.cmd::text,
    coalesce(nullif(array_to_string(p.roles, ', '), ''), 'public') as roles,
    p.qual::text,
    p.with_check::text
  from pg_policies p
  where p.schemaname = 'public'
  order by p.tablename, p.policyname;
$$;

revoke execute on function public.get_rls_policies() from public, anon, authenticated;
grant  execute on function public.get_rls_policies() to service_role;
